import './globals.css';
import type { Metadata } from 'next';
import Header from '@/components/Header';
import SearchProvider from '@/contexts/SearchContext';
import { ThemeProvider } from '@/components/theme-provider';

export const metadata: Metadata = {
  title: 'Car Rental',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <SearchProvider>
        <body>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <Header />
            {children}
          </ThemeProvider>
        </body>
      </SearchProvider>
    </html>
  );
}
